<div class="row-fluid">
    <div class="span12">
    <?php if(!$this->categories){
        echo "<h2>{$this->translate('Result not found')}</h2>";
    } else {?>
        <table class="table table-bordered">
            <tr>
                <th class="span2"><?php echo $this->translate('Name');?></th>
                <th class="span3"><?php echo $this->translate('Description');?></th>
                <th class="span2"><?php echo $this->translate('Created');?></th>
                <th class="span2"><?php echo $this->translate('User');?></th>
                <th class="span2"><?php echo $this->translate('Tag');?></th>
                <th class="span1"></th>
            </tr>
            <?foreach($this->categories as $category){?>
            <tr id="<?=$category->getId()?>">
                <td><?=$category->getName()?></td>
                <td><?=$category->getDescription()?></td>
                <td><?=$category->getDateTimeCreated()?></td>
                <td><?=$category->getUser()->getUsername()?></td>
                <td><?=$category->getTag()?></td>
                <td>
                    <span data-id="<?=$category->getId()?>" class="del">Del</span>
                    <span data-id="<?=$category->getId()?>" class="edit">
                        <a href="/blog/category/new/<?=$category->getId()?>" target="_self">Edit</a>
                    </span>
                </td>
            </tr>
            <?}?>
        </table>
    <?php }?>
    </div>
</div>

<script>
    $(function(){
        $(".del").click(function(){
            var id = $(this).data("id");
        	$.post('/blog/category/del', "id="+ id, function(result) {
        	    	$('#'+ id).hide();
        	    }
        	);
        });
    });
</script>