<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered">
            <tr>
                <th class="span2">Nome</th>
                <th class="span4">Descrizione</th>
                <th class="span1">Creato</th>
                <th class="span2">Utente</th>
                <th class="span2">Tag</th>
                <th class="span1"></th>
            </tr>
            <?foreach($this->categories as $category){?>
            <tr>
                <td><?=$category['name']?></td>
                <td><?=$category['description']?></td>
                <td><?=$category['created']?></td>
                <td><?=$category['idUser']?></td>
                <td><?=$category['tag']?></td>
                <td>
                    <span date-id="<?=$category['id']?>">Del</span>
                    <span date-id="<?=$category['id']?>">Edit</span>
                </td>
            </tr>
            <?}?>
        </table>
    </div>
</div>