<div class="row-fluid">
    <div class="span12">
    <?php if(!$this->categories){
        echo "<h2>Nessun dato inserito</h2>";
    } else {?>
        <table class="table table-bordered">
            <tr>
                <th class="span2">Nome</th>
                <th class="span4">Descrizione</th>
                <th class="span1">Creato</th>
                <th class="span2">Utente</th>
                <th class="span2">Tag</th>
                <th class="span1"></th>
            </tr>
            <?foreach($this->categories as $category){?>
            <tr id="<?=$category['id']?>">
                <td><?=$category['name']?></td>
                <td><?=$category['description']?></td>
                <td><?=$category['created']?></td>
                <td><?=$category['idUser']?></td>
                <td><?=$category['tag']?></td>
                <td>
                    <span data-id="<?=$category['id']?>" class="del">Del</span>
                    <span data-id="<?=$category['id']?>" class="edit">
                        <a href="/blog/category/new/<?=$category['id']?>" target="_self">Edit</a>
                    </span>
                </td>
            </tr>
            <?}?>
        </table>
    <?php }?>
    </div>
</div>

<script>
    $(function(){
        $(".del").click(function(){
            var id = $(this).data("id");
        	$.post('/blog/category/del', "id="+ id, function(result) {
        	    	$('#'+ id).hide();
        	    }
        	);
        });
    });
</script>