<div class="row-fluid">
    <div class="span12">
    <?php if(!$this->posts){
            echo "<h2>{$this->translate('Result not found')}</h2>";
    } else {?>
        <table class="table table-bordered">
            <tr>
                <th class="span2"><?php echo $this->translate('Title');?></th>
                <th class="span1"><?php echo $this->translate('Status');?></th>
                <th class="span3"><?php echo $this->translate('Created');?></th>
                <th class="span2"><?php echo $this->translate('User');?></th>
                <th class="span2"><?php echo $this->translate('Category');?></th>
                <th class="span2"></th>
            </tr>
            <?foreach($this->posts as $post){?>
            <tr id="<?=$post->getId()?>">
                <td><?=$post->getTitle()?></td>
                <td><?=$post->translateStatus()?></td>
                <td><?=$post->getDateTimeCreated()?></td>
                <td><?=$post->getUser()->getUsername()?></td>
                <td><?=$post->getCategory()->getName()?></td>
                <td>
                    <span data-id="<?=$post->getId()?>" class="del"><i class=icon-trash></i></span>
                    <span data-id="<?=$post->getId()?>" class="edit">
                        <a href="/blog/post/new/<?=$post->getId()?>" target="_self"><i class=icon-file></i></a>
                    </span>
                </td>
            </tr>
            <?}?>
        </table>
    <?php }?>
    </div>
</div>

<script>
    $(function(){
        $(".del").click(function(){
            var id = $(this).data("id");
        	$.post('/blog/post/del', "id="+ id, function(result) {
        	    	$('#'+ id).hide();
        	    }
        	);
        });
    });
</script>