<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row-fluid">
    <div class="span12">
        <div class="span7">
            <div class="row-fluid">
                <div class="span12">
                        <?php
                        $name = $form->get('title');
                        echo $this->formRow($name);
                        ?>
                </div>
           </div>
           <div class="row-fluid">
              <div class="span12">
                    <div class="span3">
                            <?php
                            $name = $form->get('status');
                            echo $this->formRow($name);
                            ?>
                    </div>
                    <div class="span3">
                            <?php
                            $name = $form->get('userId');
                            echo $this->formRow($name);
                            ?>
                    </div>
                    <div class="span3">
                            <?php
                            $name = $form->get('categoryId');
                            echo $this->formRow($name);
                            ?>
                    </div>
               </div>
           </div>
           <div class="row-fluid">
               <div class="span12">
                   <?php
                   $name = $form->get('content');
                   echo $this->formRow($name);
                   ?>
              </div>
           </div>
           <div class="row-fluid">
               <div class="span12">
                   <?php
                   $name = $form->get('tag');
                   echo $this->formRow($name);
                   ?>
              </div>
           </div>
           <div class="row-fluid">
               <div class="span12">
                   <?php
                   $name = $form->get('description');
                   echo $this->formRow($name);
                   ?>
              </div>
           </div>
        </div>
    </div>
    <?php echo $this->formHidden($form->get('id')) ?>
        <?php echo $this->formElement($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
</div>
<script>
    $(function(){
        // CKEDITOR.replace( 'editor' );
    });
</script>
